version: "3"

services:
  backend:
    container_name: python
    restart: always
    build: .
    command: python -u src/app.py
    ports:
      - "5000:5000"
    links:
      - database
    volumes:
      - .:/app
  database:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"
    logging:
      driver: none
